""""""""""""""
" => My .vimrc
""""""""""""""

"""""""""""""""""
" Vim-plug setup
"""""""""""""""""
" Set dir
call plug#begin('$HOME/.vim/plugged')

" Plugins

Plug 'vim-airline/vim-airline'

Plug 'vim-airline/vim-airline-themes'

Plug 'airblade/vim-gitgutter'

Plug 'w0rp/ale'

Plug 'junegunn/vim-github-dashboard'

Plug 'junegunn/goyo.vim'

Plug 'mattn/gist-vim'

Plug 'JamshedVesuna/vim-markdown-preview'

Plug 'darfink/vim-plist'

Plug 'lambdalisue/vim-pager'

Plug 'davidhalter/jedi-vim'

Plug 'jacoborus/tender.vim'

Plug 'danro/rename.vim'

" Initialize plugin system
call plug#end()

"""""""""
" Airline
"""""""""
set laststatus=2
"let g:airline_theme='molokai'
let g:airline_theme= 'tender'
let g:airline_section_b = '%{strftime("%c")}'
let g:airline_section_y = 'BN: %{bufnr("%")}'
let g:airline#extensions#tabline#enabled = 1

"""""
" UI
"""""
set nocompatible " macOS keyboard compatibility
set ignorecase " Ignore case when searching
set hlsearch " Highlight search results
set tabstop=4 " Four space tab
set shiftwidth=4 " Set autoindent
set showmatch " Show matching parentheses
set showmode " Show edit mode
set number " Show line numbers
set backspace=2 " Normalise backspace in iTerm2
set clipboard=unnamed " Use macOS clipboard
"set mouse=a " Mouse on everywhere

""""""""""""
" Formatting
""""""""""""
set wrap
set linebreak
set nolist

""""""""""""""""""
" Colors and Fonts
""""""""""""""""""
syntax on " Syntax highlighting
"colorscheme zenburn " Set colourscheme
colorscheme tender " Set colourscheme

"""""""""""""
" Keybindings
"""""""""""""
" Manage splits
nnoremap <C-J> <C-W><C-J> "Ctrl-j to move down a split  
nnoremap <C-K> <C-W><C-K> "Ctrl-k to move up a split  
nnoremap <C-L> <C-W><C-L> "Ctrl-l to move right a split  
nnoremap <C-H> <C-W><C-H> "Ctrl-h to move left a split

" Edit files in current directory
cnoremap %% <C-R>=fnameescape(expand('%:h')).'/'<cr>
map <leader>ew :e %%
map <leader>es :sp %%
map <leader>ev :vsp %%
map <leader>et :tabe %%

"""""""""""
" Shortcuts
"""""""""""
command! PU PlugUpdate | PlugUpgrade

""""""""
" .vimrc
""""""""
" Source the vimrc file after saving it
augroup reload_vimrc " {
    autocmd!
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END " }
